### ISSUE TITLE
Crashing on Background State - Null Pointer Exception -  Version : 0.15.18 / 0.15.17

### ISSUE THREAD

**Issue by abidjamil** [sahha-ai/sahha-android#118]
**Device State**
100% In background

**Logs**

Fatal Exception: java.lang.NullPointerException: Parameter specified as non-null is null: method sdk.sahha.android.domain.model.config.SahhaConfigurationKt.toSahhaSettings, parameter <this>
       at sdk.sahha.android.domain.model.config.SahhaConfigurationKt.toSahhaSettings(:2)
       at sdk.sahha.android.common.SahhaReconfigure.getSahhaSettings(SahhaReconfigure.kt:59)
       at sdk.sahha.android.common.SahhaReconfigure.access$getSahhaSettings(SahhaReconfigure.kt:17)
       at sdk.sahha.android.common.SahhaReconfigure$getSahhaSettings$1.invokeSuspend(:15)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8913)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

**Comment by min-sahha** [comment]
Hey @abidjamil , I will close this for now as it seems to be resolved, if you run into any other issues let us know! Cheers
